# Generated by Django 2.2.7 on 2019-11-19 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('capacity_validation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gp', 'general purpose'), ('w', 'weapon'), ('a', 'ammunition'), ('p', 'protection')], max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.PositiveSmallIntegerField()),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price', models.PositiveIntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Bin')),
            ],
        ),
    ]
