# Generated by Django 2.2.7 on 2019-12-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ready_to_play',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
