# Generated by Django 2.2.7 on 2019-11-29 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='creator',
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='religion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
