# Generated by Django 2.2.7 on 2019-11-17 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('capacity_validation', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='kind',
            field=models.CharField(choices=[('PC', 'player character'), ('NPC', 'non-player character')], default='PC', editable=False, max_length=2),
        ),
        migrations.AddField(
            model_name='character',
            name='money',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(default='null', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='life_points',
            field=models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='rescue_points',
            field=models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='talent_act',
            field=models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='talent_knowledge',
            field=models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='talent_social',
            field=models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('bin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='characters.Bin')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='characters.Character')),
            ],
            bases=('characters.bin',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('talent', models.CharField(choices=[('act', 'act'), ('knowledge', 'knowledge'), ('social', 'social')], max_length=2)),
                ('value', models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gp', 'general purpose'), ('w', 'weapon'), ('a', 'ammunition'), ('p', 'protection')], max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.PositiveSmallIntegerField()),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price', models.PositiveIntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Bin')),
            ],
        ),
    ]
