# Generated by Django 2.2.7 on 2019-11-18 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20191117_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='notes',
        ),
        migrations.AddField(
            model_name='character',
            name='game_master_notes',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='character',
            name='player_notes',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='bin',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bin',
            name='capacity_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='kind',
            field=models.CharField(choices=[('PC', 'player character'), ('NPC', 'non-player character')], max_length=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='life_points',
            field=models.PositiveSmallIntegerField(default=100, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('relationship', 'relationship'), ('married', 'married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=15),
        ),
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='rescue_points',
            field=models.PositiveSmallIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='talent_act',
            field=models.PositiveSmallIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='talent_knowledge',
            field=models.PositiveSmallIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='talent_social',
            field=models.PositiveSmallIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='talent',
            field=models.CharField(choices=[('act', 'act'), ('knowledge', 'knowledge'), ('social', 'social')], max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
