# Generated by Django 2.2.7 on 2019-12-13 21:44

import characters.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_ready_to_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='gross_value',
            field=characters.fields.SkillValueField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skill',
            name='include_talent_markup',
            field=models.BooleanField(default=True),
        ),
    ]
