# Generated by Django 2.2.7 on 2019-12-13 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20191213_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='rescue_points',
            new_name='rescue_points_act',
        ),
        migrations.AddField(
            model_name='character',
            name='rescue_points_knowledge',
            field=models.PositiveSmallIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='character',
            name='rescue_points_social',
            field=models.PositiveSmallIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
